// <auto-generated />
using System;
using BookingSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BookingSystem.Infrastructure.Migrations
{
    [DbContext(typeof(BookingContext))]
    [Migration("20250103121331_AlterTablePaymentStatuses_ChangeForBroker")]
    partial class AlterTablePaymentStatuses_ChangeForBroker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.AirportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Airports", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.FlightEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DepartureAirportId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DepartureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("DestinationAirportId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmptyPlaces")
                        .HasColumnType("integer");

                    b.Property<string>("NumberOfTheFlight")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlaneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("PlaneId");

                    b.ToTable("Flights", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.Outbox.BrokerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatuses", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.PlaneEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PassengersCount")
                        .HasColumnType("integer");

                    b.Property<int>("YearOfCreation")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Planes", (string)null);
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.AirportEntity", b =>
                {
                    b.HasOne("BookingSystem.Infrastructure.Entities.CountryEntity", "Country")
                        .WithMany("Airports")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.FlightEntity", b =>
                {
                    b.HasOne("BookingSystem.Infrastructure.Entities.AirportEntity", "DepartureAirport")
                        .WithMany("FlightsDeparting")
                        .HasForeignKey("DepartureAirportId");

                    b.HasOne("BookingSystem.Infrastructure.Entities.AirportEntity", "DestinationAirport")
                        .WithMany("FlightsArriving")
                        .HasForeignKey("DestinationAirportId");

                    b.HasOne("BookingSystem.Infrastructure.Entities.PlaneEntity", "Plane")
                        .WithMany("Flights")
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartureAirport");

                    b.Navigation("DestinationAirport");

                    b.Navigation("Plane");
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.AirportEntity", b =>
                {
                    b.Navigation("FlightsArriving");

                    b.Navigation("FlightsDeparting");
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.CountryEntity", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("BookingSystem.Infrastructure.Entities.PlaneEntity", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
